import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = resolve(ROOT_DIR, 'src');
const COMPONENTS_DIR = resolve(SRC_DIR, 'components');
const INDEX_OUTPUT_FILE = resolve(SRC_DIR, 'index.ts');
const REGISTER_OUTPUT_FILE = resolve(SRC_DIR, 'register.ts');

const componentDirectories = existsSync(COMPONENTS_DIR)
	? readdirSync(COMPONENTS_DIR, { withFileTypes: true })
			.filter((entry) => entry.isDirectory())
			.map((entry) => entry.name)
			.sort((a, b) => a.localeCompare(b))
	: [];

const componentExports = componentDirectories.flatMap((componentDirectory) => {
	const entryFile = resolve(COMPONENTS_DIR, componentDirectory, 'index.ts');

	if (!existsSync(entryFile)) {
		return [];
	}

	const fileContents = readFileSync(entryFile, 'utf8');
	const exportMatches = fileContents.matchAll(/export\s+\{\s*default\s+as\s+(Lx[A-Za-z0-9_]+)\s*\}/g);

	return Array.from(exportMatches, ([, componentName]) => ({
		componentDirectory,
		componentName,
	}));
});

const registerLines = [
	'// This file is auto-generated by scripts/generate-barrel.ts.',
	'import \'./styles/index.scss\';',
	'import { defineAsyncComponent, type App, type Component } from \'vue\';',
	'',
	'const componentLoaders = {',
	...componentExports.map(
		({ componentDirectory, componentName }) =>
			`\t${componentName}: () => import('./components/${componentDirectory}').then(module => module.${componentName}),`,
	),
	'} satisfies Record<string, () => Promise<Component>>;',
	'',
	'export function registerComponents(app: App, lazy?: true): void;',
	'export function registerComponents(app: App, lazy: false): Promise<void>;',
	'export function registerComponents(app: App, lazy = true): void | Promise<void> {',
	'\tif (lazy) {',
	'\t\tfor (const [componentName, loader] of Object.entries(componentLoaders)) {',
	'\t\t\tapp.component(componentName, defineAsyncComponent(loader));',
	'\t\t}',
	'',
	'\t\treturn;',
	'\t}',
	'',
	'\treturn Promise.all(',
	'\t\tObject.entries(componentLoaders).map(async ([componentName, loader]) => {',
	'\t\t\tapp.component(componentName, await loader());',
	'\t\t}),',
	'\t).then(() => undefined);',
	'}',
];

const indexLines = [
	'/* eslint-disable perfectionist/sort-exports */',
	'// This file is auto-generated by scripts/generate-barrel.ts.',
	'import \'./styles/index.scss\';',
	'',
	'export { registerComponents } from \'./register\';',
	'',
	...componentDirectories.map((componentName) => `export * from './components/${componentName}';`),
];

if (existsSync(resolve(SRC_DIR, 'directives/index.ts'))) {
	indexLines.push('export * from \'./directives\';');
}

registerLines.push('');
indexLines.push('');

await mkdir(dirname(INDEX_OUTPUT_FILE), { recursive: true });
await writeFile(REGISTER_OUTPUT_FILE, `${registerLines.join('\n')}`, 'utf8');
await writeFile(INDEX_OUTPUT_FILE, `${indexLines.join('\n')}`, 'utf8');
