import { existsSync, readdirSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = resolve(ROOT_DIR, 'src');
const COMPONENTS_DIR = resolve(SRC_DIR, 'components');
const OUTPUT_FILE = resolve(SRC_DIR, 'index.ts');

const componentExports = existsSync(COMPONENTS_DIR)
	? readdirSync(COMPONENTS_DIR, { withFileTypes: true })
			.filter((entry) => entry.isDirectory())
			.map((entry) => entry.name)
			.sort((a, b) => a.localeCompare(b))
	: [];

const lines = [
	'// This file is auto-generated by scripts/generate-barrel.ts.',
	'import \'./styles/index.scss\';',
	'',
	...componentExports.map((componentName) => `export * from './components/${componentName}';`),
];

if (existsSync(resolve(SRC_DIR, 'directives/index.ts'))) {
	lines.push('export * from \'./directives\';');
}

lines.push('');

await mkdir(dirname(OUTPUT_FILE), { recursive: true });
await writeFile(OUTPUT_FILE, `${lines.join('\n')}`, 'utf8');
