/* eslint-disable perfectionist/sort-exports */
// This file is auto-generated by scripts/generate-barrel.ts.
import './styles/index.scss';

export { registerComponents } from './register';

export * from './components/accordion';
export * from './components/alert';
export * from './components/avatar';
export * from './components/badge';
export * from './components/button';
export * from './components/card';
export * from './components/carousel';
export * from './components/details';
export * from './components/flex';
export * from './components/icon';
export * from './components/page';
export * from './components/switch';
export * from './components/tag';
export * from './directives';
