// This file is auto-generated by scripts/generate-barrel.ts.
import './styles/index.scss';
import { defineAsyncComponent, type App, type Component } from 'vue';

const componentLoaders = {
	LxAccordion: () => import('./components/accordion').then(module => module.LxAccordion),
	LxAccordionItem: () => import('./components/accordion').then(module => module.LxAccordionItem),
	LxAlert: () => import('./components/alert').then(module => module.LxAlert),
	LxAvatar: () => import('./components/avatar').then(module => module.LxAvatar),
	LxBadge: () => import('./components/badge').then(module => module.LxBadge),
	LxButton: () => import('./components/button').then(module => module.LxButton),
	LxCard: () => import('./components/card').then(module => module.LxCard),
	LxCarousel: () => import('./components/carousel').then(module => module.LxCarousel),
	LxDetails: () => import('./components/details').then(module => module.LxDetails),
	LxFlex: () => import('./components/flex').then(module => module.LxFlex),
	LxIcon: () => import('./components/icon').then(module => module.LxIcon),
	LxPage: () => import('./components/page').then(module => module.LxPage),
	LxSwitch: () => import('./components/switch').then(module => module.LxSwitch),
	LxTag: () => import('./components/tag').then(module => module.LxTag),
} satisfies Record<string, () => Promise<Component>>;

export function registerComponents(app: App, lazy?: true): void;
export function registerComponents(app: App, lazy: false): Promise<void>;
export function registerComponents(app: App, lazy = true): void | Promise<void> {
	if (lazy) {
		for (const [componentName, loader] of Object.entries(componentLoaders)) {
			app.component(componentName, defineAsyncComponent(loader));
		}

		return;
	}

	return Promise.all(
		Object.entries(componentLoaders).map(async ([componentName, loader]) => {
			app.component(componentName, await loader());
		}),
	).then(() => undefined);
}
